version: "3.9"

services:
    web:
        image: ubuntu:18.04
        build: .
        container_name: rtl-sdr-tcp
        restart: always
        devices:
            - "/dev/dvb/adapter0/dvr0:/dev/dvb/adapter0/dvr0"
        ports:
            - "1234:1234"
